### ISSUE TITLE
关于 Disable_Helper 的许可证说明

### ISSUE THREAD

**Issue by LIBPS** [Immortal-Sty/MC_resourcepacks_delHelper#1]
尊敬的 Immortal-Sty ，

您好！

这里是 LIB 临时工作室。首先，我们想要对您在使用我们的库并为其开发做出的贡献表示感谢。我们注意到您的项目 Immortal-Sty 版本在继续开发和分发我们的库时，似乎没有使用 "GNU-GENERAL PUBLIC LICENSE"协议。

我们写信是为了通知您，我们最近对我们的库采用了新的许可协议。我们希望大家都能够遵守这一协议，以保护开源社区的共同利益。

我们了解到，您可能已经对库进行了一些修改和优化，工作室非常赞赏您的工作。为了确保您的项目能够更好的切合我们的未修改版本项目，我们建议您遵循以下步骤：

1. **审查新协议**：请仔细阅读我们新采用的协议条款 GNU-GENERAL PUBLIC LICENSE（下面简称 GPL 协议)，确保您了解其中的义务和权利。

2. **合规性调整**：如果您的项目尚未遵守新协议，请您使用 GPL 协议 的许可证来标注您的项目。

3. **开源您的改动**：根据 GPL 协议的要求，任何对 GPL 授权软件的修改都需要以源代码形式公开。请确保您的所有修改都已经或即将公开。

4. **使用 Fork 复刻**：我们鼓励您使用 Fork 的方式来开发不同编程语言的版本。这样可以促进软件的多样性和创新。

如果您不打算使用 Fork 复刻，我们可以在您的项目使用 GPL 协议后，将您的（批处理文件）版本标注在我们未修改版本的首页上。
同时，您也可以将原版 https://github.com/LIBPS/disable_helper 标注在您的页面上。

感谢您的理解和合作。

**Comment by BarbTurnip437** [comment]
9

**Comment by Immortal-Sty** [comment]
#挠头 你是小蛇的朋友吧，但……其实……我早就把 `echo ...` 以外的内容全删了，我用的 win 的批处理语法，在 py 里相当于源码中只保留了 `print("...")`，其它全删了。

另外小蛇的 Python 版开发是晚于我这个库的，我与他应该算是各自分别用两种语言分别实现的差不多的功能的。

之所以提及小蛇，主要是“用批处理脚本搞定 MC 材质包”的想法是由小蛇开始的。

我不是很懂协议，我也菜鸡的，请问这种情况需要加这个协议吗？如果需要我就给加上。

另外友链是没问题的。

**Comment by LIBPS** [comment]
您可以阅读下面由 Github 官方文档，来为您的项目添加 GPL 协议
https://docs.github.com/zh/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

如果您不添加，就会导致您的开源库是 **默认实施版权法** 的。

下面是 Github 官方文档中提到的：
[您没有选择许可的义务， 但如果没有许可，就会默认实施版权法，因此您会保留对您的源代码的所有权利，任何人都不能复制、分发您的工作或创建其派生作品。 如果您创建开源项目，强烈建议您包含开源许可。](https://docs.github.com/zh/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)

**Comment by Immortal-Sty** [comment]
谢啦，原来这个有模版啊。
