### ISSUE TITLE
运行时闪退 / 添加Releases支持

### ISSUE THREAD

**Issue by BarbTurnip437** [Immortal-Sty/MC_resourcepacks_delHelper#2]
VScode 报错:
```
'募心诘乃形募魑∠钕允境隼?' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
''0'' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'叮ㄎ朔乐咕月肪队锌崭瘢?' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'_enable' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
```

双击运行直接闪退

**Comment by BarbTurnip437** [comment]
解决方法
像[我](https://github.com/LIBPS/Disable_Helper)一样移除`mack.mcmeta`检测

**Comment by Immortal-Sty** [comment]
如果没有 `pack.mcmeta`，会显示下面的文本，而不是报错。

```
当前路径错误。
请查看使用说明，并将禁用助手放至正确位置。
```

你这个更像是把文件保存成了 UTF-8 导致的。对了，还有换行，不能用 Linux 的 \n 换行（也就是 LF），要用 win 的 \r\n（也就是 CRLF），不然也会报错。

草，想起来了，git 上传的时候自动把 CRLF 转成 LF 了，我改一下。

**Comment by BarbTurnip437** [comment]
> 你这个更像是把文件保存成了 UTF-8 导致的。

这个是VScode特性 ~~(懒得搞)~~

**Comment by BarbTurnip437** [comment]
你搞一点[Releases](https://github.com/LIBPS/Disable_Helper/releases)把

**Comment by Immortal-Sty** [comment]
好了，你再看看？

**Comment by Immortal-Sty** [comment]
> 你搞一点[Releases](https://github.com/LIBPS/Disable_Helper/releases)把

感觉应该不需要吧，反正又没打包，直接点 `Code`，然后再 `Download ZIP` 就好了。
