### ISSUE TITLE
上传文件的换行符错误？

### ISSUE THREAD

**Issue by BarbTurnip437** [Immortal-Sty/MC_resourcepacks_delHelper#3]
双击运行闪退\
VScode报错
```
此时不应有 do。
```

##### ~~你不本地测试的吗~~

**Comment by Immortal-Sty** [comment]
此时是哪时？我目前用的一直是这个，没出过问题。

**Comment by BarbTurnip437** [comment]
> 此时是哪时？我目前用的一直是这个，没出过问题。

VSCode是这么说的

**Comment by Immortal-Sty** [comment]
我把 github 里的下载下来测试了一下，发现还是换行的锅，你自己用 vsc 的替换把 `\n` 全替换成 `\r\n` 吧，替换完就能用了，git 改换行符的问题等我有空了再看看咋搞。

**Comment by BarbTurnip437** [comment]
我测了
是配置文件夹的问题

**Comment by Immortal-Sty** [comment]
啊？配置文件夹会使 vsc 报语法的错吗？不应该啊？还是说是 vsc 的锅？

**Comment by BarbTurnip437** [comment]
> 啊？配置文件夹会使 vsc 报语法的错吗？不应该啊？还是说是 vsc 的锅？

不是
你看顶楼,`双击运行闪退`
是代码问题
你把配置文件夹删了运行试试

**Comment by BarbTurnip437** [comment]
不对

**Comment by BarbTurnip437** [comment]
我在桌面就没法

**Comment by BarbTurnip437** [comment]
> 我把 github 里的下载下来测试了一下，发现还是换行的锅，你自己用 vsc 的替换把 `\n` 全替换成 `\r\n` 吧，替换完就能用了，git 改换行符的问题等我有空了再看看咋搞。

好像就是这个
私密马赛

**Comment by Immortal-Sty** [comment]
先别 close，等我过两天把 git 改换行符的问题搞定了再 close。

**Comment by Immortal-Sty** [comment]
我这里试了，已经没问题了，你重新下载试试看看？

**Comment by Immortal-Sty** [comment]
那我就把关了吧，有问题再重开。

**Comment by BarbTurnip437** [comment]
:)
